[package]
name = "salazy_test"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.2.0-nightly.20260815", directory="aztec" }
salazy_contract = { path = "../salazy_contract" }
